extension kubernetes with {
  kubeConfig: ''
  namespace: context.runtime.kubernetes.namespace
} as kubernetes


//////////////////////////////////////////
// Common Radius variables
//////////////////////////////////////////

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

//////////////////////////////////////////
// PostgreSQL variables
//////////////////////////////////////////

var resourceName = context.resource.name
var namespace = context.runtime.kubernetes.namespace 
var dbSecretName = context.resource.properties.secretName
var database string = 'postgres_db'
var tag string = '16-alpine'
var port = 5432
var applicationName = context.application != null ? context.application.name : ''
// Extract last segment from environment path for labels
var environmentId     = context.resource.properties.?environment ?? ''
var environmentParts  = environmentId != '' ? split(environmentId, '/') : []
var environmentName = length(environmentParts) > 0
  ? environmentParts[length(environmentParts) - 1]
  : ''
// Extract resource group name
// Index 4 is the resource group name
var resourceGroupName = split(context.resource.id, '/')[4]
// Common labels 
var labels = {
  'radapp.io/resource':       resourceName
  'radapp.io/application':    applicationName
  'radapp.io/environment':    environmentName
  'radapp.io/resource-type':  replace(context.resource.type, '/', '-')
  'radapp.io/resource-group': resourceGroupName
}
var memory ={
  S: {
    memoryRequest: '512Mi'
  } 
  M: {
    memoryRequest: '1Gi'
  }
  L: {
    memoryRequest: '2Gi'
  }
} 

//////////////////////////////////////////
// PostgreSQL Deployment
//////////////////////////////////////////


resource postgresql 'apps/Deployment@v1' = {
  metadata: {
    name: resourceName
    namespace: namespace
    labels: labels
  }
  spec: {
    selector: {
      matchLabels: {
        app: 'postgresql'
      }
    }
    template: {
      metadata: {
        labels: {
          app: 'postgresql'
        }
      }
      spec: {
        containers: [
          {
            // This container is the running postgresql instance.
            name: 'postgres'
            image: 'postgres:${tag}'
            ports: [
              {
                containerPort: port 
              }
            ]
            resources: {
              requests: {
                memory: memory[context.resource.properties.size].memoryRequest
              }
            }
            env: [
              {
                name: 'POSTGRES_USER'
                valueFrom: {
                  secretKeyRef: {
                    name: dbSecretName
                    key: 'username'
                  }
                }
              }
              {
                name: 'POSTGRES_PASSWORD'
                valueFrom: {
                  secretKeyRef: {
                    name: dbSecretName
                    key: 'password'
                  }
                }
              }
              {
                name: 'POSTGRES_DB'
                value: database
              }
            ]
          }
        ]
      }
    }
  }
}

resource svc 'core/Service@v1' = {
  metadata: {
    name: resourceName
    namespace: namespace
    labels: labels
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      app: 'postgresql'
    }
    ports: [
      {
        port: port 
      }
    ]
  }
}

//////////////////////////////////////////
// Output Radius result 
//////////////////////////////////////////

output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${svc.metadata.namespace}/providers/core/Service/${svc.metadata.name}'
    '/planes/kubernetes/local/namespaces/${postgresql.metadata.namespace}/providers/apps/Deployment/${postgresql.metadata.name}'
  ]
  values: {
    host: '${svc.metadata.name}.${svc.metadata.namespace}.svc.cluster.local'
    port: port
    database: database
  }
}
